<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implements hook_default_services_endpoint_alter().
 */
function site_default_services_endpoint_alter(&$endpoints) {
  foreach ($endpoints as &$endpoint) {
    if (strpos($endpoint->name, 'conduit') === 0) {
      $endpoint->path = str_replace('conduit', 'api', $endpoint->path);
    }
  }
}
